kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-openshift-scc-privileged-pipeline-sa
  labels:
    Build-Name: Buildpacks-Nodejs-Simple
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: buildpacks-nodejs-simple
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'